version: '3.8'

services:
  salesforce-app:
    container_name: salesforce_pro
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Opcional: sobrescreva valores do .env
      # - SECRET_KEY=${SECRET_KEY}
      # - MASTER_KEY=${MASTER_KEY}
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./database.sqlite:/app/database.sqlite
    networks:
      - salesforce_net

networks:
  salesforce_net:
    driver: bridge
